import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { cpampAuth, cpampV2Auth, cpampV2OtherHost, cpampV2WithoutKey } from "./__fixtures__/cpampAuth";
import {
  _resetKeyCache,
  obfuscateData,
  deobfuscateData,
  readPanelAuth,
  type PanelAuth,
} from "./panelAuth";

const STORAGE_KEY = "cli-proxy-auth";

// Build a panel-style persisted auth blob: zustand persist envelope
// {state, version} serialized to JSON, then obfuscated with the shared algo.
function storePanelAuth(auth: PanelAuth): void {
  const envelope = JSON.stringify({
    state: {
      apiBase: auth.apiBase,
      managementKey: auth.managementKey,
      rememberPassword: true,
    },
    version: 0,
  });
  localStorage.setItem(STORAGE_KEY, obfuscateData(envelope));
}

describe("panelAuth obfuscation", () => {
  it("round-trips through obfuscate/deobfuscate", () => {
    const original = JSON.stringify({ state: { apiBase: "http://h:1", managementKey: "k" } });
    expect(deobfuscateData(obfuscateData(original))).toBe(original);
  });
});

describe("readPanelAuth", () => {
  const realSelf = window.self;
  const realTop = window.top;

  beforeEach(() => {
    localStorage.clear();
    _resetKeyCache();
  });

  afterEach(() => {
    vi.restoreAllMocks();
    localStorage.clear();
    _resetKeyCache();
    // Restore embedded state.
    Object.defineProperty(window, "self", { value: realSelf, configurable: true });
    Object.defineProperty(window, "top", { value: realTop, configurable: true });
  });

  function setEmbedded(embedded: boolean) {
    // window.self !== window.top → embedded
    Object.defineProperty(window, "self", { value: window, configurable: true });
    Object.defineProperty(window, "top", {
      value: embedded ? ({} as Window) : window,
      configurable: true,
    });
  }

  it("returns null when not embedded (direct page open)", () => {
    setEmbedded(false);
    storePanelAuth({ apiBase: "http://127.0.0.1:8317", managementKey: "secret-xyz" });
    expect(readPanelAuth()).toBeNull();
  });

  it("reads apiBase + managementKey when embedded and remember-password was set", () => {
    setEmbedded(true);
    storePanelAuth({ apiBase: "http://127.0.0.1:8317", managementKey: "secret-xyz" });
    expect(readPanelAuth()).toEqual({
      apiBase: "http://127.0.0.1:8317",
      managementKey: "secret-xyz",
    });
  });

  it("returns null when managementKey is empty (remember password unchecked)", () => {
    setEmbedded(true);
    const envelope = JSON.stringify({
      state: { apiBase: "http://h:1", managementKey: "", rememberPassword: false },
      version: 0,
    });
    localStorage.setItem(STORAGE_KEY, obfuscateData(envelope));
    expect(readPanelAuth()).toBeNull();
  });

  it("returns null when nothing is stored", () => {
    setEmbedded(true);
    expect(readPanelAuth()).toBeNull();
  });

  it("returns null when the stored value is garbage", () => {
    setEmbedded(true);
    localStorage.setItem(STORAGE_KEY, "not-valid-json-or-obfuscated");
    expect(readPanelAuth()).toBeNull();
  });

  it("reads the saved v2 auth generated by CPAMP without rewriting storage", () => {
    setEmbedded(true);
    expect(window.location.host).toBe("localhost:3000");
    localStorage.setItem(STORAGE_KEY, cpampV2Auth);
    const setItem = vi.spyOn(Storage.prototype, "setItem");
    const removeItem = vi.spyOn(Storage.prototype, "removeItem");
    expect(readPanelAuth()).toEqual(cpampAuth);
    expect(localStorage.getItem(STORAGE_KEY)).toBe(cpampV2Auth);
    expect(setItem).not.toHaveBeenCalled();
    expect(removeItem).not.toHaveBeenCalled();
  });

  it("keeps v1 and v2 decoding independent when both formats are encountered", () => {
    setEmbedded(true);
    const legacy = { apiBase: "http://localhost:8317", managementKey: "legacy-test-key" };
    storePanelAuth(legacy);
    expect(readPanelAuth()).toEqual(legacy);
    localStorage.setItem(STORAGE_KEY, cpampV2Auth);
    expect(readPanelAuth()).toEqual(cpampAuth);
    storePanelAuth(legacy);
    expect(readPanelAuth()).toEqual(legacy);
  });

  it("restores v2 after a browser user agent change", () => {
    setEmbedded(true);
    localStorage.setItem(STORAGE_KEY, cpampV2Auth);
    vi.spyOn(window.navigator, "userAgent", "get").mockReturnValue("Changed browser after update");
    _resetKeyCache();
    expect(readPanelAuth()).toEqual(cpampAuth);
  });

  it.each([
    ["another host", cpampV2OtherHost],
    ["password not remembered", cpampV2WithoutKey],
    ["malformed base64", "enc::v2::%%%"],
    ["unsupported version", cpampV2Auth.replace("enc::v2::", "enc::v3::")],
  ])("does not restore invalid v2 authentication: %s", (_label, value) => {
    setEmbedded(true);
    localStorage.setItem(STORAGE_KEY, value);
    expect(readPanelAuth()).toBeNull();
  });

  it("does not reuse v2 auth when opened outside the panel iframe", () => {
    setEmbedded(false);
    localStorage.setItem(STORAGE_KEY, cpampV2Auth);
    expect(readPanelAuth()).toBeNull();
  });

  it("falls back when the browser denies storage access", () => {
    setEmbedded(true);
    vi.spyOn(Storage.prototype, "getItem").mockImplementation(() => { throw new Error("Storage denied"); });
    expect(readPanelAuth()).toBeNull();
  });
});
