// Generated by CPAMP v1.14.1's real obfuscateData(), not the plugin encoder.
// Source: aa8c5e9886b42ec82d78a419a1e1f59700ca90c5, apps/web/src/utils/encryption.ts.
// Source SHA256: 5a90a53909201633d43b51e29229a9ce0355bddcbf5bc557fd77e379969ee4c0.
// The first two fixtures use the Vitest browser host localhost:3000.
export const cpampAuth = {
  apiBase: "https://panel.example.test",
  managementKey: "synthetic-manager-key",
};

export const cpampV2Auth = "enc::v2::GE4aWREGClpDVkMRGUQ1BBEQSwAYGxEXBQFfAlwEDhwEC0sZDlMRHAMGTxgNHAdWFhFdUV4CCwxAFRwbMxxUQ0pLXg4LFh0MTlMQSA4UHARKFgZCGQQeR1BUQBkBCg4DCRo/EgdJRF9CVEFWHV8FFxJUW1sEAhpEGAtAT1lH";
export const cpampV2WithoutKey = "enc::v2::GE4aWREGClpDVkMRGUQ1BBEQSwAYGxEXBQFfAlwEDhwEC0sZDlMRHAMGTxgNHAdWFhFCVV0GAQtIAiIOCwpaDgIND00DAxkaX0dfRxUQABZEHBpNSFEa";
// Generated for another.example.test; it must not decode on localhost:3000.
export const cpampV2OtherHost = "enc::v2::GE4aWREGClpDVkMRGUQ1BBEQSwAYGxEXBQFfAlwEDhwEC0sZDlMREQIKWhwAAVpHVEMAEQIESREIFhoXJwxUUkhNCwBDFRgMWR4GTxgIVFsUABFYGQBUUVhNAAQKABEUVw4xDxwHHwoASkdCFR8FCRgCVhMWBhAFBkNSSF8F";
